name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-12 cmake libcurl4-openssl-dev libfmt-dev

    # Configure compiler
    - name: Set GCC 12 as default compiler
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 60
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 60
        gcc --version
        g++ --version

    # Configure the project
    - name: Configure project
      run: |
        mkdir -p build
        cmake -B build -S cli_app \
          -DCMAKE_CXX_STANDARD=20 \
          -DCMAKE_CXX_STANDARD_REQUIRED=ON

    # Build the project
    - name: Build project
      run: cmake --build build

    # Run tests
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
