name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libcurl4-openssl-dev libgtest-dev

      # Build GoogleTest in the home directory
      - name: Build GoogleTest
        run: |
          mkdir -p $HOME/gtest/build && cd $HOME/gtest/build
          cmake /usr/src/googletest && make

      # Configure and build the project
      - name: Configure CMake project
        run: |
          mkdir -p build
          cmake -S . -B build -DCMAKE_PREFIX_PATH=$HOME/gtest/build

      - name: Build project
        run: |
          cmake --build build

      # Run tests
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
