name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upgrade GCC
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt-get update
        sudo apt-get install -y gcc-12 g++-12
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 12
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 12
        gcc --version
        g++ --version

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          libcurl4-openssl-dev \
          libgtest-dev \
          zlib1g-dev \
          libfmt-dev
          
    - name: Build GoogleTest
      run: |
          cd /usr/src/googletest
          sudo cmake -DBUILD_SHARED_LIBS=ON .
          sudo make
          sudo cp lib/*.so /usr/lib

    - name: Configure CMake with GCC 12
      env:
        CC: gcc-12
        CXX: g++-12
      run: |
        cmake -S . -B build -DCMAKE_CXX_COMPILER=g++-12 -DCMAKE_C_COMPILER=gcc-12 -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu

    - name: Build project
      run: cmake --build build

    - name: Run tests
      run: ctest --test-dir build
