name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Install GCC-13 and set it as the default compiler
    - name: Install GCC-13
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt-get update
        sudo apt-get install -y gcc-13 g++-13
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 13
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 13
        gcc --version
        g++ --version

    # 3. Install necessary dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          libcurl4-openssl-dev \
          zlib1g-dev \
          libfmt-dev \
          build-essential  # Ensures basic build tools are available

    # 4. Configure the CMake build
    - name: Configure CMake with GCC-13
      env:
        CC: gcc-13
        CXX: g++-13
      run: |
        mkdir -p build
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc-13 -DCMAKE_CXX_COMPILER=g++-13

    # 5. Build the project
    - name: Build project
      run: cmake --build build -- -j$(nproc)

    # 6. Run tests
    - name: Run tests
      run: ctest --test-dir build --output-on-failure
